### ISSUE TITLE
Client tools not available

### ISSUE THREAD

**Issue by LorenzBischof** [appuio/ops-techlab#27]
The following link in lab 3.2 doesn't show a link to the extensions: https://console.user[X].lab.openshift.ch/console/extensions/clients/

The package `atomic-openshift-clients-redistributable` cannot be installed on `master1`

**Comment by mebagel** [comment]
Probably because atomic-openshift-clients-redistributable was excluded in /etc/yum.conf. 
atomic-openshift-clients-redistributable package will be pre-installed on all masters in the future.
