### ISSUE TITLE
add descriptions to persistent storage chapter

### ISSUE THREAD

**Issue by nerrehmit** [appuio/ops-techlab#32]
Add some description to the chapter about "persistent storage" https://github.com/appuio/ops-techlab/blob/master/labs/333_persistent_storage.md

Some more info on storageclass would have been helpful for me.

**Comment by dvob** [comment]
@nerrehmit is this coverd by #58 ?

**Comment by bliemli** [comment]
Please open a new issue if this was not fixed with #58.
